---
# Copyright 2017, taseer94@gmail.com
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: congress_apt_packages.yml

- name: install pip packages
  pip:
    name: "{{ item }}"
  with_items:
    - virtualenv

- name: clone congress repo
  git:
    repo: "{{ congress_git_repo }}"
    dest: /opt/congress
    clone: yes

- name: create congress group
  group:
    name: "{{ congress_system_group_name }}"
    state: present

- name: create congress user
  user:
    name: "{{ congress_system_user_name }}"
    group: "{{ congress_system_group_name }}"
    createhome: no

- name: make congress configuration directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/congress
    - /etc/congress/snapshot

#- name: generate configuration file
#  shell: tox -egenconfig
# args:
#    chdir: /opt/congress

#- name: copy files
#  copy:
#    src: "/opt/congress/etc/{{ item }}"
#    dest: /etc/congress
#  with_items:
#    - api-paste.ini
#    - policy.json
#    - congress.conf.sample
